name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get -y install docker.io
        sudo service docker start

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: utsavjpatel
        DOCKER_PASSWORD: Whyshouldi@14
      run: |
        docker build -t yourdockerhubusername/yourimage:latest .
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push yourdockerhubusername/yourimage:latest
